### PR TITLE
Add check for linked options

### PR DESCRIPTION
**Pull request by thinca**
Sometimes I see a linked option like `|'ignorecase'|`.
This should not be link notation.

This PR adds a check for this.

### CODE REVIEW

**Comment by machakann** [comment]
Thank you, I like this.

One thing,  could you use the error number 8 instead of 7 for it? The error number 7 has been used but obsoleted before. Therefore, it is, indeed, a vacancy now but I rather want to keep it as it is, just in case.

https://github.com/machakann/vim-vimhelplint/commit/89113746c2117242425b832a799a4182b08fb41b

**Comment by thinca** [comment]
OK.  I updated the error number, and also updated help document.

**Comment by machakann** [comment]
Thank you!

**Comment by bhcleek** [comment]
~Why is it wrong to use link notation on an option?~

Edit: nevermind, I see that options can jumped to even without the link notation.

**Pull request merged**
